### ISSUE TITLE
Sharing is not working

### ISSUE THREAD

**Issue by tiagoefreitas** [jparyani/Lychee#1]
Sharing does not show the url in Sandstorm

**Comment by jparyani** [comment]
So it's a little bit unclear, but all you have to do is click the share button and then copy the address in your web browser's address bar. Perhaps the UI should be more clear about this? Maybe when clicking share, it should say something like "You can now share this url", but there's not a lot of space in that dropdown. Any ideas?

**Comment by tiagoefreitas** [comment]
I saw that in the screenshots, but for me in the Demo server the address pop up does not appear, only the "make private" button.
Maybe it's a demo limitation?

**Comment by jparyani** [comment]
Sorry, I wan't more clear before, but I removed the address pop up. This is because grain's don't actually know their address. It's up to the user to copy the url from the address bar themselves.

**Comment by tiagoefreitas** [comment]
Sorry I didn't read your reply properly.

I think Sandstorm needs an API for the app to generate urls and show then in the UI...it's common for file hosting with sharing capabilities to be able to select a file or folder in the ui and create several different urls without changing the current page.
Also in Lychee if I share two albums they get the same url with a number in front, like 
https://demo.sandstorm.io/grain/QzHyJwDQCHQW7GxfGHCgAE/#1
https://demo.sandstorm.io/grain/QzHyJwDQCHQW7GxfGHCgAE/#2

This is a problem as I don't want to give access to both, and even with different passwords this leaks the album names.

**Comment by jparyani** [comment]
Unfortunately this is probably my fault in porting the Lychee app as-is. A more ideal Sandstorm app would have exactly 1 album inside each grain, and you would only share using Sandstorm's sharing model (most of which is unimplemented at the moment). However, this is not the case for Lychee, and it even has in-app sharing that doesn't really map well to Sandstorm's.

For now the, the best solution is to make separate grains for separate albums you wish to share. Eventually we can revisit this when Sandstorm's sharing is implemented, and when we have some folder apps (tentatively named Sandbags) that would handle collecting these grains together in one nice view.

**Comment by CoolkcaH** [comment]
That makes sense, but it can create confusion for users in the meanwhile. Maybe it would be appropriate to have a list of current limitations to each app and how they will be solved by Sandstorm in the future. Moving this to sandstorm-dev mailing list

**Comment by tiagoefreitas** [comment]
That makes sense, but it can create confusion for users in the meanwhile. Maybe it would be appropriate to have a list of current limitations to each app and how they will be solved by Sandstorm in the future. Moving this discussion to sandstorm-dev mailing list

**Comment by jparyani** [comment]
I've changed the UI to be a bit more clear. You can try it out with:

https://alpha.sandstorm.io/install/6b122c5b3a3376a4793b57fb84bb6536?url=http://sandstorm.io/apps/jparyani/lychee-4.spk

**Comment by tiagoefreitas** [comment]
Just tested, that helps to mitigate the UI issue for now.
