### ISSUE TITLE
Is the plugins/extensions usable with sandstorm port?

### ISSUE THREAD

**Issue by asoderq** [jparyani/Lychee#17]
Hi,

just discovered Lychee and Sandstorm, looks awesome. Is the plugins/extensions usable with the sandstorm port? I just want to figure out how to get my pictures there in a convenient way.

Mostly I am interested in the lycheesync tool.

**Comment by jparyani** [comment]
The Sandstorm environment is different in many ways from the normal un-sandboxed Lychee server. A quick glance at https://github.com/GustavePate/lycheesync makes me think it's not a normal plugin, and it seems to require direct access to the MySQL database, which would be very problematic to get working under Sandstorm.

Simpler plugins/extensions could be included in the package, but it requires someone to test that they work properly under Sandstorm. I'm happy to accept PRs for tested plugins :)
