### ISSUE TITLE
A new Lychee grain does not let me do anything.

### ISSUE THREAD

**Issue by dwrensha** [jparyani/Lychee#4]
It looks like this:

<img width="1203" alt="lychee" src="https://cloud.githubusercontent.com/assets/495768/9562215/02b5e2ec-4e34-11e5-97d6-318a59f6b6af.png">

There's nowhere to click to make anything happen.

**Comment by jparyani** [comment]
Fixed in 46c16fe70b507e5b227ea9bec4e08ea505e0b8e4.

An update that tried to fix it so public viewing worked accidentally turned everyone into public viewers, even the admin :)

Also, this reminded me, I'm adding roles so you can share an admin link as well as a public link.

Thanks!
