### ISSUE TITLE
nginx default file size limit is pretty low

### ISSUE THREAD

**Issue by zarvox** [jparyani/Lychee#6]
The default nginx `client_max_body_size` is limiting the size of pictures and media that can be uploaded to 1MB: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size .  I see in the git history you originally had this unlimited, and that config must have been lost in the `vagrant-spk` transition.

Let's make this unlimited?  (I should probably adjust the `vagrant-spk` defaults to do the same.)

Consider doing likewise for any other packages you switched from custom nginx configs to `vagrant-spk` ones...

**Comment by zarvox** [comment]
(see review in https://apps.sandstorm.io/app/z6rj6js4h8p8rjz2myp3dwmv3mcfv40qyfdn0d7714qxzvzvq3w0 which alerted me to the issue)

**Comment by jparyani** [comment]
Thanks for reporting!
