### ISSUE TITLE
error "Photo type not supported!" for certain jpeg images

### ISSUE THREAD

**Issue by dwrensha** [jparyani/Lychee#7]
If I try to upload the attached photo, I get a "Photo type not supported!" error. The upload POST request returns a 200, so the problem isn't that nginx is limiting the upload size.

![meetup](https://cloud.githubusercontent.com/assets/495768/11101643/13482b38-8886-11e5-9bae-649181232054.jpg)

**Comment by jeffcpullen** [comment]
Same issue with a jpg image that is 3888x2592, 3.5 MB

2500x1667, 1.6 MB - Worked
3000x2000, 2.2 MB - Failed 
3000x2000, 197 kB - Worked

So there seems to be a filesize limit around 2 MB

**Comment by dominicporter** [comment]
A bit more info from the Console:

11:47:41.620 Object { description: "Upload failed. Server returned the …", params: XMLHttpRequest, response: "Error: Photo type not supported!" }1 main.js:7:7870
lychee.error() main.js:7
s/r.onload() main.js:9

**Comment by funwhilelost** [comment]
I'm getting the same thing.  That message is specifically from the block evaluating `exif_imagetype` on the tmp file.  Locally (on my Macbook with PHP 5.5) my JPEG files all return 2 IMAGETYPE_JPEG - which should pass.  

I had a number of them work below 2 MB so I'm thinking @jeffcpullen is on to something.

**Comment by jparyani** [comment]
This was fixed thanks to #11. I tested and it appears to now work with an 11MB jpg. New version should hit the app market shortly.
